services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: investments_control
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    volumes:
      - investments_database:/bitnami/postgresql
volumes:
  investments_database: